# Generated by Django 6.0.4 on 2026-04-16 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='midia',
            name='questao',
        ),
        migrations.RemoveField(
            model_name='historicouso',
            name='tipo_acao',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='dificuldade',
        ),
        migrations.AddField(
            model_name='questao',
            name='tipo_questao',
            field=models.CharField(choices=[('MULTIPLA_ESCOLHA', 'Múltipla Escolha'), ('VERDADEIRO_FALSO', 'Verdadeiro ou Falso'), ('ABERTA', 'Aberta (Dissertação)')], default='MULTIPLA_ESCOLHA', max_length=20),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicouso',
            name='formato_exportacao',
            field=models.CharField(default='JSON', help_text='Ex: JSON, PDF, XML', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_coordenador', models.BooleanField(default=False, help_text='Marque para dar poderes de Coordenador. Desmarque para perfil Professor.')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Coordenador',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='Midia',
        ),
    ]
